CREATE TABLE curricula_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE curricula_courses
  ADD COLUMN
    author_id INTEGER REFERENCES curricula_users(id)
    ON DELETE SET NULL;
